apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-cm-broken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-cm-broken
  template:
    metadata:
      labels:
        app: web-app-cm-broken
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          env:
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: web-app-config
                  key: GREETING
