apiVersion: batch/v1
kind: Job
metadata:
  name: job-fail-onfailure
  namespace: rbac-lab
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: worker
          image: busybox:1.36
          command: ["sh", "-c", "echo 'failing on purpose' && exit 1"]
