apiVersion: batch/v1
kind: Job
metadata:
  name: job-success
  namespace: rbac-lab
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: busybox:1.36
          command: ["sh", "-c", "echo 'Job work completed' && exit 0"]
