apiVersion: v1
kind: Pod

metadata:
  name: sidecar-demo
  labels:
    app: sidecar-demo

spec:
  containers:
    - name: writer
      image: busybox:1.36
      command: ["sh", "-c", "while true; do echo $(date) >> /var/log/app/output.log; sleep 5; done"]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/app

    - name: reader
      image: busybox:1.36
      command: ["sh", "-c", "tail -f /var/log/app/output.log"]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/app

  volumes:
    - name: log-volume
      emptyDir: {}
