apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable
  namespace: resource-lab
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      resources:
        requests:
          cpu: "50m"
          memory: "32Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"
