apiVersion: v1
kind: Pod
metadata:
  name: qos-guaranteed
  namespace: resource-lab
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"
